### ISSUE TITLE
Upgrade pg_query dependency to 1.3.0

### ISSUE THREAD

**Issue by paulgaumer** [lunatic-cat/pg_exec_array_params#8]
Hi @razum2um,

arm64-based machines cannot install the gem due to the dependency `pg_query 1.2.0` not supporting arm. 
The version 1.3.0 adds support to ARM and should solve the issue ([see Changelog](https://github.com/lfittl/pg_query/blob/master/CHANGELOG.md#130-----2020-12-28)).

I am facing the issue on a M1 macbook and it might happen more and more as the new mac hardware transitions to ARM.

Would it be possible to upgrade the dependency to 1.3.0? 

([See this issue for reference](https://github.com/lfittl/pg_query/issues/185))

**Comment by razum2um** [comment]
Closed with https://github.com/lunatic-cat/pg_exec_array_params/pull/9
